/**
 * All languages supported by OpenAI Whisper for transcription.
 *
 * Each entry maps a human-readable language name to its Whisper CLI language code.
 * Sorted alphabetically by language name.
 * "auto" is also included as an option for auto-detection.
 */
export const LANGUAGES = [
  { label: "Auto-detect", value: "" },
  { label: "Abkhaz", value: "ab" },
  { label: "Acehnese", value: "ace" },
  { label: "Acholi", value: "ach" },
  { label: "Afar", value: "aa" },
  { label: "Afrikaans", value: "af" },
  { label: "Albanian", value: "sq" },
  { label: "Alur", value: "alz" },
  { label: "Amharic", value: "am" },
  { label: "Arabic", value: "ar" },
  { label: "Armenian", value: "hy" },
  { label: "Assamese", value: "as" },
  { label: "Avar", value: "av" },
  { label: "Awadhi", value: "awa" },
  { label: "Aymara", value: "ay" },
  { label: "Azerbaijani", value: "az" },
  { label: "Balinese", value: "ban" },
  { label: "Baluchi", value: "bal" },
  { label: "Bambara", value: "bm" },
  { label: "Baoulé", value: "bci" },
  { label: "Bashkir", value: "ba" },
  { label: "Basque", value: "eu" },
  { label: "Batak Karo", value: "btx" },
  { label: "Batak Simalungun", value: "bts" },
  { label: "Batak Toba", value: "bbc" },
  { label: "Belarusian", value: "be" },
  { label: "Bemba", value: "bem" },
  { label: "Bengali", value: "bn" },
  { label: "Betawi", value: "bew" },
  { label: "Bhojpuri", value: "bho" },
  { label: "Bikol", value: "bik" },
  { label: "Bosnian", value: "bs" },
  { label: "Breton", value: "br" },
  { label: "Bulgarian", value: "bg" },
  { label: "Buryat", value: "bua" },
  { label: "Cantonese", value: "yue" },
  { label: "Catalan", value: "ca" },
  { label: "Cebuano", value: "ceb" },
  { label: "Chamorro", value: "ch" },
  { label: "Chechen", value: "ce" },
  { label: "Chichewa", value: "ny" },
  { label: "Chinese (Simplified)", value: "zh" },
  { label: "Chinese (Traditional)", value: "zh" },
  { label: "Chuukese", value: "chk" },
  { label: "Chuvash", value: "cv" },
  { label: "Corsican", value: "co" },
  { label: "Crimean Tatar (Cyrillic)", value: "crh" },
  { label: "Crimean Tatar (Latin)", value: "crh" },
  { label: "Croatian", value: "hr" },
  { label: "Czech", value: "cs" },
  { label: "Danish", value: "da" },
  { label: "Dari", value: "fa" },
  { label: "Dhivehi", value: "dv" },
  { label: "Dinka", value: "din" },
  { label: "Dogri", value: "doi" },
  { label: "Dombe", value: "dov" },
  { label: "Dutch", value: "nl" },
  { label: "Dyula", value: "dyu" },
  { label: "Dzongkha", value: "dz" },
  { label: "English", value: "en" },
  { label: "Esperanto", value: "eo" },
  { label: "Estonian", value: "et" },
  { label: "Ewe", value: "ee" },
  { label: "Faroese", value: "fo" },
  { label: "Fijian", value: "fj" },
  { label: "Filipino", value: "tl" },
  { label: "Finnish", value: "fi" },
  { label: "Fon", value: "fon" },
  { label: "French", value: "fr" },
  { label: "French (Canada)", value: "fr" },
  { label: "Frisian", value: "fy" },
  { label: "Friulian", value: "fur" },
  { label: "Fulani", value: "ff" },
  { label: "Ga", value: "gaa" },
  { label: "Galician", value: "gl" },
  { label: "Georgian", value: "ka" },
  { label: "German", value: "de" },
  { label: "Greek", value: "el" },
  { label: "Guarani", value: "gn" },
  { label: "Gujarati", value: "gu" },
  { label: "Haitian Creole", value: "ht" },
  { label: "Hakha Chin", value: "cnh" },
  { label: "Hausa", value: "ha" },
  { label: "Hawaiian", value: "haw" },
  { label: "Hebrew", value: "he" },
  { label: "Hiligaynon", value: "hil" },
  { label: "Hindi", value: "hi" },
  { label: "Hmong", value: "hmn" },
  { label: "Hungarian", value: "hu" },
  { label: "Hunsrik", value: "hrx" },
  { label: "Iban", value: "iba" },
  { label: "Icelandic", value: "is" },
  { label: "Igbo", value: "ig" },
  { label: "Ilocano", value: "ilo" },
  { label: "Indonesian", value: "id" },
  { label: "Inuktut (Latin)", value: "iu" },
  { label: "Inuktut (Syllabics)", value: "iu" },
  { label: "Irish", value: "ga" },
  { label: "Italian", value: "it" },
  { label: "Jamaican Patois", value: "jam" },
  { label: "Japanese", value: "ja" },
  { label: "Javanese", value: "jw" },
  { label: "Jingpo", value: "kac" },
  { label: "Kalaallisut", value: "kl" },
  { label: "Kannada", value: "kn" },
  { label: "Kanuri", value: "kr" },
  { label: "Kapampangan", value: "pam" },
  { label: "Kazakh", value: "kk" },
  { label: "Khasi", value: "kha" },
  { label: "Khmer", value: "km" },
  { label: "Kiga", value: "cgg" },
  { label: "Kikongo", value: "kg" },
  { label: "Kinyarwanda", value: "rw" },
  { label: "Kituba", value: "ktu" },
  { label: "Kokborok", value: "trp" },
  { label: "Komi", value: "kv" },
  { label: "Konkani", value: "gom" },
  { label: "Korean", value: "ko" },
  { label: "Krio", value: "kri" },
  { label: "Kurdish (Kurmanji)", value: "ku" },
  { label: "Kurdish (Sorani)", value: "ckb" },
  { label: "Kyrgyz", value: "ky" },
  { label: "Lao", value: "lo" },
  { label: "Latgalian", value: "ltg" },
  { label: "Latin", value: "la" },
  { label: "Latvian", value: "lv" },
  { label: "Ligurian", value: "lij" },
  { label: "Limburgish", value: "li" },
  { label: "Lingala", value: "ln" },
  { label: "Lithuanian", value: "lt" },
  { label: "Lombard", value: "lmo" },
  { label: "Luganda", value: "lg" },
  { label: "Luo", value: "luo" },
  { label: "Luxembourgish", value: "lb" },
  { label: "Macedonian", value: "mk" },
  { label: "Madurese", value: "mad" },
  { label: "Maithili", value: "mai" },
  { label: "Makassar", value: "mak" },
  { label: "Malagasy", value: "mg" },
  { label: "Malay", value: "ms" },
  { label: "Malay (Jawi)", value: "ms" },
  { label: "Malayalam", value: "ml" },
  { label: "Maltese", value: "mt" },
  { label: "Mam", value: "mam" },
  { label: "Manx", value: "gv" },
  { label: "Maori", value: "mi" },
  { label: "Marathi", value: "mr" },
  { label: "Marshallese", value: "mh" },
  { label: "Marwadi", value: "mwr" },
  { label: "Mauritian Creole", value: "mfe" },
  { label: "Meadow Mari", value: "mhr" },
  { label: "Meiteilon (Manipuri)", value: "mni" },
  { label: "Minang", value: "min" },
  { label: "Mizo", value: "lus" },
  { label: "Mongolian", value: "mn" },
  { label: "Myanmar (Burmese)", value: "my" },
  { label: "Nahuatl (Eastern Huasteca)", value: "nhe" },
  { label: "Ndau", value: "ndc" },
  { label: "Ndebele (South)", value: "nr" },
  { label: "Nepalbhasa (Newari)", value: "new" },
  { label: "Nepali", value: "ne" },
  { label: "NKo", value: "nqo" },
  { label: "Norwegian", value: "no" },
  { label: "Nuer", value: "nus" },
  { label: "Occitan", value: "oc" },
  { label: "Odia (Oriya)", value: "or" },
  { label: "Oromo", value: "om" },
  { label: "Ossetian", value: "os" },
  { label: "Pangasinan", value: "pag" },
  { label: "Papiamento", value: "pap" },
  { label: "Pashto", value: "ps" },
  { label: "Persian", value: "fa" },
  { label: "Polish", value: "pl" },
  { label: "Portuguese (Brazil)", value: "pt" },
  { label: "Portuguese (Portugal)", value: "pt" },
  { label: "Punjabi (Gurmukhi)", value: "pa" },
  { label: "Punjabi (Shahmukhi)", value: "pa" },
  { label: "Quechua", value: "qu" },
  { label: "Qʼeqchiʼ", value: "kek" },
  { label: "Romani", value: "rom" },
  { label: "Romanian", value: "ro" },
  { label: "Rundi", value: "rn" },
  { label: "Russian", value: "ru" },
  { label: "Sami (North)", value: "se" },
  { label: "Samoan", value: "sm" },
  { label: "Sango", value: "sg" },
  { label: "Sanskrit", value: "sa" },
  { label: "Santali (Latin)", value: "sat" },
  { label: "Santali (Ol Chiki)", value: "sat" },
  { label: "Scots Gaelic", value: "gd" },
  { label: "Sepedi", value: "nso" },
  { label: "Serbian", value: "sr" },
  { label: "Sesotho", value: "st" },
  { label: "Seychellois Creole", value: "crs" },
  { label: "Shan", value: "shn" },
  { label: "Shona", value: "sn" },
  { label: "Sicilian", value: "scn" },
  { label: "Silesian", value: "szl" },
  { label: "Sindhi", value: "sd" },
  { label: "Sinhala", value: "si" },
  { label: "Slovak", value: "sk" },
  { label: "Slovenian", value: "sl" },
  { label: "Somali", value: "so" },
  { label: "Spanish", value: "es" },
  { label: "Sundanese", value: "su" },
  { label: "Susu", value: "sus" },
  { label: "Swahili", value: "sw" },
  { label: "Swati", value: "ss" },
  { label: "Swedish", value: "sv" },
  { label: "Tahitian", value: "ty" },
  { label: "Tajik", value: "tg" },
  { label: "Tamazight", value: "ber" },
  { label: "Tamazight (Tifinagh)", value: "ber" },
  { label: "Tamil", value: "ta" },
  { label: "Tatar", value: "tt" },
  { label: "Telugu", value: "te" },
  { label: "Tetum", value: "tet" },
  { label: "Thai", value: "th" },
  { label: "Tibetan", value: "bo" },
  { label: "Tigrinya", value: "ti" },
  { label: "Tiv", value: "tiv" },
  { label: "Tok Pisin", value: "tpi" },
  { label: "Tongan", value: "to" },
  { label: "Tshiluba", value: "lua" },
  { label: "Tsonga", value: "ts" },
  { label: "Tswana", value: "tn" },
  { label: "Tulu", value: "tcy" },
  { label: "Tumbuka", value: "tum" },
  { label: "Turkish", value: "tr" },
  { label: "Turkmen", value: "tk" },
  { label: "Tuvan", value: "tyv" },
  { label: "Twi", value: "tw" },
  { label: "Udmurt", value: "udm" },
  { label: "Ukrainian", value: "uk" },
  { label: "Urdu", value: "ur" },
  { label: "Uyghur", value: "ug" },
  { label: "Uzbek", value: "uz" },
  { label: "Venda", value: "ve" },
  { label: "Venetian", value: "vec" },
  { label: "Vietnamese", value: "vi" },
  { label: "Waray", value: "war" },
  { label: "Welsh", value: "cy" },
  { label: "Wolof", value: "wo" },
  { label: "Xhosa", value: "xh" },
  { label: "Yakut", value: "sah" },
  { label: "Yiddish", value: "yi" },
  { label: "Yoruba", value: "yo" },
  { label: "Yucatec Maya", value: "yua" },
  { label: "Zapotec", value: "zap" },
  { label: "Zulu", value: "zu" },
] as const

export type LanguageCode = (typeof LANGUAGES)[number]["value"]

/** Look up a language code by its label. Returns "" for auto-detect if not found. */
export function languageCodeForLabel(label: string): LanguageCode {
  const found = LANGUAGES.find((l) => l.label === label)
  return found ? found.value : ""
}

/** Look up a language label by its code. Returns "Auto-detect" if not found. */
export function languageLabelForCode(code: string): string {
  const found = LANGUAGES.find((l) => l.value === code)
  return found ? found.label : "Auto-detect"
}
